name: paper_board
description: Powerful and highly customizable flutter drawing canvas
version: 0.0.1
homepage: https://github.com/stevenosse/paper_board

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  iconsax_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
