name: paper_board

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: App Facing package

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Download dependencies
        run: flutter pub get
        working-directory: ${{env.source-directory}}

      - name: Run Flutter Format
        run: dart format --set-exit-if-changed .
        working-directory: ${{env.source-directory}}
     
      - name: Run Flutter Analyzer
        run: flutter analyze
        working-directory: ${{env.source-directory}}

      # Build Android version of the example App
      # - name: Run Android build
      #   run: flutter build apk --release
      #   working-directory: example

      # Build iOS version of the example App
      # - name: Run iOS build
      #   run: flutter build ios --release --no-codesign
      #   working-directory: example

      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --coverage
        working-directory: ./